Repository WildCodeSchool/orleans-php-202103-project-clubimmo, pull requests merged in 2021-05, with the labels that each got.

#122 S04 US22 adding the delete option to the admin section
  src/Controller/AdminAdvertisementController.php
  src/View/Admin/Advertisement/index.html.twig
Labels: Reviewed

#128 S04 US23 adding a Description input to the admin form
  .gitignore
  src/Controller/AdminAdvertisementController.php
  src/Model/PropertyManager.php
  src/View/Admin/Advertisement/add.html.twig
Labels: Reviewed

#104 S03US09 BIEN EN AVANT SUR PAGE ACCUEIL
  database.sql
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/PhotoManager.php
  src/Model/PropertyManager.php
  src/Model/PropertyTypeManager.php
  src/Model/SectorManager.php
  src/View/Home/_carousel.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#133 changed controler and model for carousel take photos by property id
  src/Controller/PropertyController.php
  src/View/Advertisement/_carousel.html.twig
Labels: Conflict resolved, Reviewed

#130 S03 us19 advertisement contact
  .gitignore
  composer.json
  composer.lock
  config/mail.php.dist
  public/index.php
  src/Controller/ContactController.php
  src/Controller/ItemController.php
  src/View/Contact/email.html.twig
  src/View/Contact/index.html.twig
Labels: Conflict resolved, Reviewed

#132 changed map for it changed by sector
  database.sql
  public/assets/css/advertisement.css
  src/Controller/PropertyController.php
  src/View/Advertisement/_energyInformations.html.twig
  src/View/Advertisement/index.html.twig
Labels: Conflict resolved, Reviewed

#123 S04 us20 admin upload
  .gitignore
  public/assets/css/admin_advertisement.css
  src/Controller/AdminAdvertisementController.php
  src/Model/PropertyManager.php
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
Labels: Conflict resolved, Reviewed

#137 Sprint 5: 1st merge
  .gitignore
  composer.json
  composer.lock
  config/mail.php.dist
  database.sql
  public/assets/css/admin_advertisement.css
  public/assets/css/advertisement.css
  public/assets/css/style.css
  public/index.php
  src/Controller/AdminAdvertisementController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/PropertyController.php
  src/Model/PhotoManager.php
  src/Model/PropertyManager.php
  src/Model/PropertyTypeManager.php
  src/Model/SectorManager.php
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
  src/View/Advertisement/_carousel.html.twig
  src/View/Advertisement/_energyInformations.html.twig
  src/View/Advertisement/index.html.twig
  src/View/Contact/email.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_carousel.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#129 S03 us12 search bar
  README.md
  adminForm.sql
  database.sql
  property.sql
  public/assets/css/property.css
  public/assets/css/style.css
  src/Controller/AdminAdvertisementController.php
  src/Controller/PropertyController.php
  src/Model/PropertyManager.php
  src/View/Property/index.html.twig
Labels: Reviewed

#109 S03 us17 advertisement details icons
  database.sql
  public/assets/css/advertisement.css
  public/assets/css/flaticonFont/flaticon.css
  public/assets/css/flaticonFont/flaticon.eot
  public/assets/css/flaticonFont/flaticon.svg
  public/assets/css/flaticonFont/flaticon.ttf
  public/assets/css/flaticonFont/flaticon.woff
  public/assets/css/flaticonFont/flaticon.woff2
  src/Controller/PropertyController.php
  src/Model/PropertyFeatureManager.php
  src/Model/PropertyManager.php
  src/View/Advertisement/_carousel.html.twig
  src/View/Advertisement/_feature.html.twig
  src/View/Advertisement/index.html.twig
Labels: Conflict resolved, Reviewed

#136 chaanges vars because of new database
  config/mail.php copy.dist
  src/View/Advertisement/_header.html.twig
Labels: Reviewed

#135 added details and description of property
  public/assets/css/advertisement.css
  src/View/Advertisement/_details.html.twig
  src/View/Advertisement/index.html.twig
Labels: Conflict resolved, Reviewed

#138 Sprint 5 PUSH3
  README.md
  adminForm.sql
  config/mail.php copy.dist
  database.sql
  property.sql
  public/assets/css/advertisement.css
  public/assets/css/flaticonFont/flaticon.css
  public/assets/css/flaticonFont/flaticon.eot
  public/assets/css/flaticonFont/flaticon.svg
  public/assets/css/flaticonFont/flaticon.ttf
  public/assets/css/flaticonFont/flaticon.woff
  public/assets/css/flaticonFont/flaticon.woff2
  public/assets/css/property.css
  public/assets/css/style.css
  src/Controller/AdminAdvertisementController.php
  src/Controller/PropertyController.php
  src/Model/PropertyFeatureManager.php
  src/Model/PropertyManager.php
  src/View/Advertisement/_carousel.html.twig
  src/View/Advertisement/_details.html.twig
  src/View/Advertisement/_feature.html.twig
  src/View/Advertisement/_header.html.twig
  src/View/Advertisement/index.html.twig
  src/View/Property/index.html.twig
Labels: Reviewed

#111 Modified the style of merged pages
  README.md
  database.sql
  public/assets/css/admin_advertisement.css
  public/assets/css/agency.css
  public/assets/css/contact.css
  public/assets/css/header.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/accueil.jpg
  public/assets/images/diagnostic.jpg
  public/assets/images/dpe2.jpeg
  public/assets/images/e-mail.png
  public/assets/images/entretien-jardin.jpg
  public/assets/images/fax.png
  public/assets/images/image_accueil.jpg
  public/assets/images/logo_temporary.jpg
  public/assets/images/opening.png
  public/assets/images/phone.png
  public/index.html
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/header.html.twig
  src/View/Home/infoAgence.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
Labels: Conflict resolved, Reviewed

#140 Sprint 5: 4th merge
  .gitignore
  README.md
  database.sql
  public/assets/css/admin_advertisement.css
  public/assets/css/agency.css
  public/assets/css/contact.css
  public/assets/css/header.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/accueil.jpg
  public/assets/images/diagnostic.jpg
  public/assets/images/dpe2.jpeg
  public/assets/images/e-mail.png
  public/assets/images/entretien-jardin.jpg
  public/assets/images/fax.png
  public/assets/images/image_accueil.jpg
  public/assets/images/logo_temporary.jpg
  public/assets/images/opening.png
  public/assets/images/phone.png
  public/index.html
  src/Controller/AdminAdvertisementController.php
  src/Model/PhotoManager.php
  src/Model/PropertyFeatureManager.php
  src/Model/PropertyManager.php
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/header.html.twig
  src/View/Home/infoAgence.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
Labels: Reviewed

#157 Issue 14 fix problemes generaux
  config/mail.php.dist
  src/Controller/PropertyController.php
  src/View/Advertisement/_header.html.twig
Labels: Reviewed

#158 added navbar size var
  public/assets/css/navbar.css
  public/assets/css/style.css
Labels: Reviewed

#159 Fix issues 1, 2, 3, 5 and reorganised the property cards
  README.md
  public/assets/css/header.css
  public/assets/css/navbar.css
  public/assets/css/property.css
  public/assets/css/style.css
  src/View/Contact/index.html.twig
  src/View/Home/_carousel.html.twig
  src/View/Home/header.html.twig
  src/View/Home/infoAgence.html.twig
  src/View/Property/index.html.twig
Labels: Reviewed

#160 Fix footer links
  src/Model/PropertyManager.php
  src/View/Includes/_footer.html.twig
Labels: Conflict resolved, Reviewed

#163 Fix searchbar responsive
  public/assets/css/property.css
  public/assets/css/style.css
  src/View/Home/_carousel.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Property/index.html.twig
Labels: Conflict resolved, Reviewed

#166 FIX8_adminAddRef fixing the reference creation
  src/Controller/AdminAdvertisementController.php
  src/Model/PropertyManager.php
Labels: Reviewed

#165 added colors for h4,5 and6
  public/assets/css/style.css
Labels: Reviewed

#167 Fix property surface room
  src/Model/FeatureManager.php
  src/Model/PropertyManager.php
Labels: Changes requested

#168 Fix color
  public/assets/css/agency.css
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#169 fix home page
  src/View/Home/_carousel.html.twig
Labels: Reviewed

#170 correction because code was broken
  public/uploads/60940cbd8d138_advertisement6.jpg
  src/Model/PropertyManager.php
Labels: Reviewed

#172 changed code for display photos because was broken
  public/uploads/60940f27e70f3_advertisement6.jpg
  src/View/Advertisement/_carousel.html.twig
  src/View/Home/_carousel.html.twig
  src/View/Property/index.html.twig
Labels: Reviewed
