Repository WildCodeSchool/orleans-php-202103-project-clubimmo, pull requests merged in 2021-04, with the labels that each got.

#3 first commit of Project 2
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: Reviewed

#22 S01 us01 footer
  public/assets/css/style.css
  public/assets/images/dpe2.png
  src/View/Home/index.html.twig
  src/View/Includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#26 adding the proper fonts, sizes and colours to the css
  public/assets/css/style.css
Labels: Corrections done, Reviewed

#38 S02 us01 navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/accueil.jpg
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Conflict resolved, Reviewed

#39 S02 us02 header
  public/assets/css/header.css
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Conflict resolved, Reviewed

#62 First merger, sprint 2
  public/assets/css/header.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/accueil.jpg
  public/assets/images/dpe2.png
  src/Controller/HomeController.php
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#64 S02 us07 infoagence
  public/assets/css/agency.css
  public/assets/css/style.css
  public/assets/images/dpe2.jpeg
  public/assets/images/dpe2.png
  src/View/Home/index.html.twig
  src/View/Home/infoAgence.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#63 S02 us06 page property affichage de biens
  README.md
  property.sql
  public/assets/css/property.css
  src/Controller/PropertyController.php
  src/Model/PropertyManager.php
  src/View/Includes/_navbar.html.twig
  src/View/Property/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#65 Second Merge - Spint 2
  README.md
  property.sql
  public/assets/css/agency.css
  public/assets/css/property.css
  public/assets/css/style.css
  public/assets/images/dpe2.jpeg
  public/assets/images/dpe2.png
  src/Controller/PropertyController.php
  src/Model/PropertyManager.php
  src/View/Home/index.html.twig
  src/View/Home/infoAgence.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Property/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#59 S02 us01 advertisement
  README.md
  database.sql
  public/assets/css/style.css
  public/assets/images/no_image.png
  src/Controller/AdvertisementController.php
  src/Model/PhotoManager.php
  src/View/Advertisement/_carousel.html.twig
  src/View/Advertisement/index.html.twig
  src/View/Property/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#66 S02 us08 admin page
  src/Controller/AdminAdvertisementController.php
  src/View/Admin/Advertisement/index.html.twig
Labels: Reviewed

#95 Sprint 3 : First merge
  src/Controller/AdminAdvertisementController.php
  src/View/Admin/Advertisement/index.html.twig
Labels: Reviewed

#96 S03 us11 admin add
  public/assets/css/admin_advertisement.css
  src/Controller/AdminAdvertisementController.php
  src/Model/PropertyManager.php
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
Labels: Reviewed

#98 S03 us18 admin bigger form
  adminForm.sql
  database.sql
  src/Controller/AdminAdvertisementController.php
  src/View/Admin/Advertisement/add.html.twig
Labels: Reviewed

#60 S02 us02 advertisement ges
  README.md
  database.sql
  public/assets/css/style.css
  public/assets/images/DPE.png
  public/assets/images/GES.png
  src/Controller/AdvertisementController.php
  src/Controller/PropertyController.php
  src/View/Advertisement/_energyInformations.html.twig
  src/View/Advertisement/index.html.twig
  src/View/Property/index.html.twig
Labels: Conflict resolved, Reviewed

#106 Sprint 3 : second push
  README.md
  adminForm.sql
  database.sql
  public/assets/css/admin_advertisement.css
  public/assets/css/style.css
  public/assets/images/DPE.png
  public/assets/images/GES.png
  src/Controller/AdminAdvertisementController.php
  src/Controller/AdvertisementController.php
  src/Controller/PropertyController.php
  src/Model/PropertyManager.php
  src/View/Admin/Advertisement/add.html.twig
  src/View/Admin/Advertisement/index.html.twig
  src/View/Advertisement/_energyInformations.html.twig
  src/View/Advertisement/index.html.twig
  src/View/Property/index.html.twig
Labels: Reviewed

#105 Us05 page contact
  README.md
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Property/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#110 Sprint 3 : third merge
  README.md
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Property/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#94 S02 us03 advertisement header
  README.md
  public/assets/css/advertisement.css
  public/assets/css/style.css
  src/Controller/PropertyController.php
  src/View/Advertisement/_header.html.twig
  src/View/Advertisement/index.html.twig
Labels: Changes requested

#112 Sprint 3 : 4th merge
  README.md
  public/assets/css/advertisement.css
  public/assets/css/style.css
  src/Controller/PropertyController.php
  src/View/Advertisement/_header.html.twig
  src/View/Advertisement/index.html.twig
Labels: Reviewed
